---
apiVersion: v1
kind: Namespace
metadata:
    name: $org

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $pvName
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: $pvName
  nfs:
    path: $path
    server: 192.168.1.206

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $org
 name: $pvName
spec:
 accessModes:
   - ReadWriteMany
 storageClassName: $pvName
 resources:
   requests:
     storage: 10Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $pvDataName
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: $pvDataName
  nfs:
    path: $datapath
    server: 192.168.1.206

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $org
 name: $pvDataName
spec:
 accessModes:
   - ReadWriteMany
 storageClassName: $pvDataName
 resources:
   requests:
     storage: 10Gi
